- name: Decrypt secret files in vault.yaml and place them in secret-files directory
  hosts: local
  gather_facts: no
  tasks:

  - name: Ensure secret-files/vars directory exists
    file:
      path: "{{ inventory_dir }}/secret-files/vars"
      state: directory

  - name: Decrypt files and put in secret-files directory
      # note we have to use base64 command because Ansible copy contents doesn't support binary or trailing newlines
    shell: "printf '{{ item.value }}' | base64 --decode > {{ inventory_dir }}/secret-files/{{ item.key }}"
    with_dict: "{{ plaintext_files }}"
    no_log: true

    # secret_files variable is a hash like this:

    # secret_files:
    #   file_42: "---base64 encoded string---"
    #   another_file: "..another base64 encoded string representing the file's contents..."

  - name: Decrypt
