- name: Encrypt secret files and keys

  # Each file in the secret-files directory is converted to a base64 string,
  # then added to file "vault.yaml" as an element of the variable "secret_files".
  # The element is a key/value pair, the key is the filename and the value is the base64 encoded file.

  # Then we use ansible-vault to encrypt the vault.yaml file, move it to group_vars/local.
  # Then each file in the secret-files/vars directory is encrypted as well.

  hosts: local
  gather_facts: no
  tasks:

  - name: get rid of old encrypted directory and all its contents
    file:
      path: "{{ inventory_dir }}/group_vars/local/encrypted"
      state: absent

  - name: create new encrypted directory to hold encrypted files
    file:
      path: "{{ inventory_dir }}/group_vars/local/encrypted"
      state: directory

    # vault.yaml creates variables that look like this:

    # secret_files:
    #   file_42: base64 encoded string
    #   another_file: another base64 encoded string representing the contents of the file
    #   ...

  - name: create secrets file secret-files/temp/vault.yaml
    file:
      path: "{{ inventory_dir }}/secret-files/temp"
      state: directory

  - copy:
      dest: "{{ inventory_dir }}/secret-files/temp/vault.yaml"
      content: "secret_files:\n"

  - name: add entries to vault.yaml representing the secret files
    # note: have to use linux/osx base64 command because Ansible lookup('file') does not preserve final newline character
    shell: "echo \"  {{ item | basename }}: $(base64 < {{ item }})\" >> {{ inventory_dir }}/secret-files/temp/vault.yaml"
    with_fileglob:
    - "{{ inventory_dir }}/secret-files/*"

  - name: copy all the secret variable files in secret-files/vars to secret-files/temp
    shell: "cp {{ inventory_dir }}/secret-files/vars/*.yaml {{ inventory_dir }}/secret-files/temp/"

  - name: encrypt all the secret YAML files in secret-files/temp
    command: "ansible-vault encrypt  --vault-password-file={{ inventory_dir }}/vault-password {{ item }}"
    with_fileglob:
    - "{{ inventory_dir }}/secret-files/temp/*.yaml"

  - name: move all the encrypted YAML files to group_vars/local/encrypted
    shell: "mv {{ inventory_dir }}/secret-files/temp/*.yaml {{ inventory_dir }}/group_vars/local/encrypted/"

  - name: remove the secret-files/temp directory
    file:
      path: "{{ inventory_dir }}/secret-files/temp"
      state: absent

  - include: roles/misc/tasks/add-to-git.yaml

