- name: Bootstrap the CoreOS cluster server
  hosts: master
  become: yes
  gather_facts: no
  roles:
  - coreos-bootstrap-server

- name: Bootstrap the CoreOS cluster clients
  hosts:
  - etcd
  - worker
  become: yes
  gather_facts: no
  roles:
  - coreos-bootstrap-client
