
- name: get rid of old encrypted files
  file:
    path: "{{ inventory_dir }}/files/encrypted"
    state: absent

- name: recreate the directory structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ inventory_dir }}/files/encrypted/vars/all"
  - "{{ inventory_dir }}/files/secret"
  - "{{ inventory_dir }}/files/public"

- name: If needed, create vault-password file with random password for encryption
  command: "true {{ lookup('password', env + '/vault-password chars=ascii_letters') }}"
  args:
    creates: "{{ env }}/vault-password"

- name: Encrypt all the secret files
  command: "openssl aes-256-cbc -e -a -kfile {{ inventory_dir }}/vault-password -in {{ item }} -out {{ inventory_dir }}/files/encrypted/{{ item | basename }}"
  with_fileglob:
  - "{{ inventory_dir }}/files/secret/*"

- name: Encrypt all the secret vars files
  command: "openssl aes-256-cbc -e -a -kfile {{ inventory_dir }}/vault-password -in {{ item }} -out {{ inventory_dir }}/files/encrypted/vars/all/{{ item | basename }}"
  with_fileglob:
  - "{{ inventory_dir }}/group_vars/all/secret/*"
