- name: create secret directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ inventory_dir }}/files/secret"
  - "{{ inventory_dir }}/group_vars/all/secret"

- name: Decrypt all the encrypted files
  command: "openssl aes-256-cbc -d -a -kfile {{ inventory_dir }}/vault-password -in {{ item }} -out {{ inventory_dir }}/files/secret/{{ item | basename }}"
  with_fileglob:
  - "{{ inventory_dir }}/files/encrypted/*"

- name: Decrypt all the encrypted vars files
  command: "openssl aes-256-cbc -d -a -kfile {{ inventory_dir }}/vault-password -in {{ item }} -out {{ inventory_dir }}/group_vars/all/secret/{{ item | basename }}"
  with_fileglob:
  - "{{ inventory_dir }}/files/encrypted/vars/all/*"
